### ISSUE TITLE
Complete examples

### ISSUE THREAD

**Issue by TylerBloom** [boxbeam/untwine#1]
I'm looking over the crate and noticed that there are not complete example or explanations. This has made it relatively difficult to parse out (no pun intended) how use the crate. While the JSON example is helpful for building a parser, it requires some tinkering. An explanation of the syntax would be helpful. Additionally, it would help to know how things get translated into Rust type. New folks to the crate need to adopt a mental model. What should that mental model be? The fact that something like `rest=.*` yields a `Vec<char>` was very surprising. Also, when should I prefix something with a `$`?

More importantly, there is not a single example (both in the repo and in the docs page) about how to consume the parser. All of the example in the repo using the `parser_repl`. I had to look at that function's source code in order to figure out what to do. It would be amazing to have start to finish examples in the docs pages so that it is clear how to use the crate.

**Comment by boxbeam** [comment]
I would advise reading https://docs.rs/untwine/latest/untwine/macro.parser.html#summary-of-pattern-syntax, and you can use the functions `untwine::parse` and `untwine::parse_pretty` to use your parsers. I can work on some better examples in the doc home and readme.

**Comment by TylerBloom** [comment]
Thanks. That definitely helps explain how to leverage the syntax of the parser. It is still unclear to me what exactly is being generated. As someone who is new to the crate, I don't know how to think about what it is doing. It certainly feels like high-level regex but the interface (both in creating the parser and using `parse`) is wildly different.

This is to say that I've enjoyed porting part of my project to use this crate, and I think others would as well. But part of encouraging its wider use (if that is something you're interested in) is making the docs more holistic.

**Comment by boxbeam** [comment]
Yeah, thanks for the feedback! I'm currently writing a better guide.

**Comment by boxbeam** [comment]
@TylerBloom Would you mind checking out https://github.com/boxbeam/untwine/blob/master/TUTORIAL.md and letting me know your thoughts?

**Comment by daxhuiberts** [comment]
@boxbeam I stumbled on your tutorial yesterday and looking at the commits (and this issue) I realized you just added it.

I want to thank you for creating the tutorial. It's very clear and builds up nicely explaining the essential concepts of the parser macro.

Untwine is such an amazing approach to parser generators. Thank you for creating it ❤️

**Comment by boxbeam** [comment]
@daxhuiberts Thanks so much for the feedback! I'm so glad the tutorial was clear and that the library is achieving its purpose.

**Comment by boxbeam** [comment]
Marking this one as completed 😁

**Comment by TylerBloom** [comment]
Sorry for the delayed response, but I just read it, and everything looks good. It's very helpful!
