### ISSUE TITLE
Composibility

### ISSUE THREAD

**Issue by TylerBloom** [boxbeam/untwine#2]
Sorry for the back-to-back issues, but these seems separate, so I didn't want to bog down the first issue.

I'm using untwine to write a command parser for a "CLI" running inside of a TUI. Its been nice so far, but there is an annoyance with calling parsers from other parsers. What I would like to do is parse the top level command and then parse subcommands for that command in the function block. However, pulling out the tail of a tail of a string (via `rest=.*`) returns a `Vec<char>`, which then has to be parsed into a `String` in order to get a `&str`.

It would be nice to have syntax for "everything else", perhaps `..`. If possible, it would be even better if this could be placed anywhere, not just at the end of a sequence (for example, if your data is suffixed).

**Comment by boxbeam** [comment]
I would recommend using `rest=<.*>` in this case, it will capture as a `&str`

**Comment by boxbeam** [comment]
Note that repeating patterns are greedy in untwine, so there's no good way to do something like `"start" .* "end"`. If you want to do that, you need to use a greedy match which cannot consume the terminal token.

**Comment by TylerBloom** [comment]
Excellent, thanks! `rest=<.*>` fits my needs.
